### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by jiaqiAA** [zf223669/Persona_Gestor#1]
Wonderful work! Is the code releasing any time soon?

**Comment by zf223669** [comment]
Thank you very much for paying attention to our work. 
We will publish the source code later. Please wait patiently.

**Comment by jiaqiAA** [comment]
Hello, could you provide a Google Drive link for the pre-trained model?

**Comment by zf223669** [comment]
OK， We are preparing the Google Drive link

**Comment by zf223669** [comment]
Hi, we have uploaded all the processed_data and pre-trained model to the google drive, the link: [https://drive.google.com/drive/folders/1qgdBb2LgpW4hhmtOb3I9o_qysoQ4qVCP?usp=drive_link](url)

**Comment by zf223669** [comment]
Hi, we have uploaded all the processed_data and pre-trained model to the google drive, the link: 
[https://drive.google.com/drive/folders/1qgdBb2LgpW4hhmtOb3I9o_qysoQ4qVCP?usp=drive_link](url)

**Comment by zf223669** [comment]
Hi, we have uploaded all the processed_data and pre-trained model to the google drive, the link:
[https://drive.google.com/drive/folders/1qgdBb2LgpW4hhmtOb3I9o_qysoQ4qVCP?usp=drive_link](https://drive.google.com/drive/folders/1qgdBb2LgpW4hhmtOb3I9o_qysoQ4qVCP?usp=drive_link)

**Comment by jiaqiAA** [comment]
Hi, when I run
`python src/diffmotion/diffmotion_trainer/train_diffmotion.py -m experiment=Trinity_Inference_WavLM_large.yaml` described in `README`.
The error message "Could not find 'experiment/Trinity_Inference_WavLM_large.yaml'". I think the name is wrong, and I change it to `ZEGGS_WavLM_large_generate.yaml`. 
I meet another error `Cannot find primary config 'train_diffmotion_v2.yaml'.` and I change `train_diffmotion_v2.yaml'.` to `train_diffmotion.yaml`
Then I meet `ModuleNotFoundError: No module named 'src.utils.LDM'`,  line 17-20
https://github.com/zf223669/Persona_Gestor/blob/266dce5d978cd79808dc3814e9d09d432d6757d4/src/diffmotion/diffmotion_module/diffmotion_multi_test_module.py#L17
and there is no `trinityLDM`  in `src.diffmotion.components`
https://github.com/zf223669/Persona_Gestor/blob/266dce5d978cd79808dc3814e9d09d432d6757d4/src/diffmotion/components/ddim_util/util.py#L18

**Comment by zf223669** [comment]
Hi， I fixed the Bug. Could you try again?  If you have any questions, please don't hesitate to give me feedback.

**Comment by jiaqiAA** [comment]
Hi, there is no file `src/data/BEAT_Only_Audio/prepare_BEAT_datasets.py` described in [README](https://github.com/zf223669/Persona_Gestor#5-inference-by-using-in-the-wild-speech-audio) , and if I want to use my own audio files, how can I prepare it. I think the code for handling audio in the wild is missing. In `src/data/Data_Processing`, there is only code for `BEAT` and `Trinity`.

**Comment by zf223669** [comment]
Hi, I have uploaded the code, please try again.

**Comment by jiaqiAA** [comment]
Thanks. I'll use my own audio files to test it later.
When I run `python src/diffmotion/diffmotion_trainer/train_diffmotion.py -m experiment=ZEGGS_WavLM_large_generate.yaml`, I got the results. I noticed that from the first frame to the last frame, the orientation of the character's body gradually rotates in a certain direction, and there are sudden changes in the displacement of the root bone.
the first frame:
![屏幕截图 2024-04-30 173252](https://github.com/zf223669/Persona_Gestor/assets/63891270/028e770c-ffa5-44d3-9e5c-4d05ffc657c6)
the last frame:
![屏幕截图 2024-04-30 173307](https://github.com/zf223669/Persona_Gestor/assets/63891270/f63259a3-63b6-43a9-907a-48e4def9a2e1)

**Comment by zf223669** [comment]
yeap.this is the issue of this method. but the beat is better发自我的手机-------- 原始邮件 --------发件人： jiaqiAA ***@***.***>日期： 2024年4月30日周二 17:35收件人： zf223669/Persona_Gestor ***@***.***>抄送： FanZhang ***@***.***>, Comment ***@***.***>主    题： Re: [zf223669/Persona_Gestor] Code release (Issue #1)
Thanks. I'll use my own audio files to test it later.
When I run python src/diffmotion/diffmotion_trainer/train_diffmotion.py -m experiment=ZEGGS_WavLM_large_generate.yaml, I got the results. I noticed that from the first frame to the last frame, the orientation of the character's body gradually rotates in a certain direction, and there are sudden changes in the displacement of the root bone.
the first frame:
2024-04-30.173252.png (view on web)
the last frame:
2024-04-30.173307.png (view on web)

**Comment by jiaqiAA** [comment]
Hi, I didn't find this problem in the [presentation page](https://zf223669.github.io/Diffmotion-v2-website/). How did you deal with this problem?

**Comment by zf223669** [comment]
We recorded the video with the camera  facing the skeleton. and the rotation is that Cumulative error when the sqeuence is too long. but we clip the videos in 10-20 sec that is not obvious.发自我的手机-------- 原始邮件 --------发件人： jiaqiAA ***@***.***>日期： 2024年5月6日周一 11:04收件人： zf223669/Persona_Gestor ***@***.***>抄送： FanZhang ***@***.***>, Comment ***@***.***>主    题： Re: [zf223669/Persona_Gestor] Code release (Issue #1)
Hi, I didn't find this problem in the presentation page. How did you deal with this problem?
